# Generated by Django 2.0.1 on 2019-01-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('course_number', models.IntegerField(default=0, verbose_name='course_number')),
                ('description', models.TextField(default='This is blank', verbose_name='description')),
            ],
        ),
    ]
