# Generated by Django 2.0.1 on 2019-01-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_hubcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubcourse',
            name='area',
            field=models.CharField(default='', max_length=16, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='hubcourse',
            name='subarea',
            field=models.CharField(default='', max_length=16, verbose_name='subarea'),
        ),
    ]
