# Generated by Django 2.0.1 on 2019-01-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='APClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination', models.CharField(max_length=64, verbose_name='examination')),
                ('score', models.CharField(max_length=16, verbose_name='score')),
                ('course_equivalent', models.CharField(max_length=64, verbose_name='course_equivalent')),
                ('bu_hub_area', models.CharField(max_length=64, verbose_name='bu_hub_area')),
            ],
        ),
    ]
