# Generated by Django 2.0.1 on 2019-01-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_apclasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apclasses',
            name='bu_hub_area',
            field=models.CharField(blank=True, max_length=64, verbose_name='bu_hub_area'),
        ),
    ]
