# Generated by Django 2.0.1 on 2019-01-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190127_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualHubCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_course_name', models.CharField(max_length=128, verbose_name='title_course_name')),
                ('subareas', models.TextField(verbose_name='subareas')),
            ],
        ),
    ]
